# Put configuration options here

# Enable full N-key roll over. This may prevent the keyboard from working with some BIOS/UEFI versions.
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT=y